services:
  ngrok:
    image: ngrok/ngrok:latest
    network_mode: host
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--url=${NGROK_URL}"
      - "8080"