# Generated by Django 6.0.3 on 2026-04-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.IntegerField(help_text='Duração em minutos')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('completed', 'Concluído'), ('canceled', 'Cancelado')], default='scheduled', max_length=20)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamento.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentxService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamento.appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamento.service')),
            ],
        ),
    ]
